### ISSUE TITLE
为什么写了MediaRecorderUtil不用

### ISSUE THREAD

**Issue by hlz2516** [rianlu/ReversalChallenge#1]
您好，最近在参考你的demo，看你写了MediaRecorderUtil不用，反而用AudioRecordUtil更麻烦了，其实用MediaRecorderUtil输出.amr的文件然后直接用RxFFmpeg转mp3也是OK的。  
一个小小的建议，换回MediaRecorderUtil，这样ffmpeg的命令也可以少打一点（当然如果您已经退坑安卓就算了）

**Comment by rianlu** [comment]
> 您好，最近在参考你的demo，看你写了MediaRecorderUtil不用，反而用AudioRecordUtil更麻烦了，其实用MediaRecorderUtil输出.amr的文件然后直接用RxFFmpeg转mp3也是OK的。 一个小小的建议，换回MediaRecorderUtil，这样ffmpeg的命令也可以少打一点（当然如果您已经退坑安卓就算了）

这个写的比较早了，当时也不太会，所以写完发现转不来就又换了种写法哈哈哈，如果其实RxFFmpeg可以换成mobile-ffmpeg，体积更小些

**Comment by hlz2516** [comment]
明白，RxFFmpeg不知道为啥gradle配置依赖导不进来，我还是clone这个项目到本地编成aar再导入我的项目的。如果有跟我遇到一样问题的小萌新可以换成mobile-ffmpeg，这个是保证可以导进来的。
